AWSTemplateFormatVersion: 2010-09-09

Parameters:
  s3Bucket:
    Type: String
    Value: s3-test-provision-2021
Resources:
  TestBucket:    
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref s3Bucket
